language: node_js
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - os: windows
node_js:
  - 12
env:
  - NODE_ENV=ci YARN_GPG=no
  - NODE_ENV=ci-staging YARN_GPG=no
cache: yarn
script:
  - yarn build
  - yarn test